### ISSUE TITLE
 unresolved dependencies

### ISSUE THREAD

**Issue by M-Aitisam** [NeshOfficial/ai25-python#17]
The current codebase fails to run due to unresolved dependencies. The dependencies are not listed in the documentation, making it difficult to install them correctly. Additionally, the code throws errors when trying to execute certain functions.

**Comment by Muhammad-Awab** [comment]
Hi  Aitisam,  

Resolved the issue by identifying and adding the missing dependencies to the `dependencies.conf` file. Updated the installation steps in the documentation to include specific commands for installing dependencies: `sudo apt-get install -f dependencies.conf`. The code now runs successfully, and all functions execute without errors. Please pull the latest changes, install dependencies, and test.
