### ISSUE TITLE
Some configurations aren't working properly in ai21/tokenizers/__init__.py

### ISSUE THREAD

**Issue by faizan6557** [NeshOfficial/ai25-python#5]
Hello team, at the location of ai21/tokenizers/__init__.py
I have found some of the issues with the commands. Infact this whole isnt working properly. If you guys can have a look into it.
Thank you !

**Comment by rehan985** [comment]
Hello, we are regretful that you need to face this issue.The appropriate solution to this error is that first to run system upgrade command then go for next. This way you won't be problematic.
Regards
