### ISSUE TITLE
FeedBack For HTTP_Client

### ISSUE THREAD

**Issue by M-Aitisam** [NeshOfficial/ai25-python#6]
Install the dependency  to  the code .   At line no 6 of the code seems like  Numpythe library is missing.  After making this, app is runnning smooth.

**Comment by Muhammad-Awab** [comment]
Hello M-Aitisam, yeah we have just got this issue from our internal team as well. We have fixed the issue.Hope so now onwards you will experince a smooth working.

Please install the necessary dependency for the code. It appears that the NumPy library is missing at line 6. Once this is addressed, the application should run smoothly.
